disabled_rules:
- cyclomatic_complexity
- function_body_length
- statement_position
- trailing_whitespace
- line_length
- todo
- type_name
- vertical_whitespace
- void_return

included:
  - Sources
  - Tests

variable_name:
  excluded:
    - id
    - in
    - x
    - y
    - dx
    - dy
