# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

before_install:
  - brew update
  - gem install cocoapods --pre

script:
  - set -o pipefail && xcodebuild test -workspace Example/KeyboardKit.xcworkspace -scheme KeyboardKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
